name: advanced-react
region: ams

services:
- dockerfile_path: backend/Dockerfile
  github:
    branch: main
    deploy_on_push: true
    repo: Asjas/advanced-react
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: advanced-react
  routes:
  - path: /
  source_dir: backend
